version: "3.8"
services:
  backend:
    image: "amigoscode/springboot-react-fullstack:10.8.2021.14.31.42"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
